kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-cfg
data:
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}