{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}
  labels:
{{ include "kubernetes-event-exporter.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-event-exporter.fullname" . }}-nodes
subjects:
  - kind: ServiceAccount
    name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}